### ISSUE TITLE
Consume TypeScript API Wrapper

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#175]
# Epic

## Description

Sovity will soon build a new API with API Clients that include TypeScript due to good compatibility with generation tools.

https://github.com/sovity/PMO-Software/issues/92

## Work Breakdown

- [x] https://github.com/sovity/edc-extensions/issues/185
- [x] Consume API Wrapper Client Library
- [x] https://github.com/sovity/edc-ui/issues/230
- [ ] https://github.com/sovity/edc-ui/issues/231
- [ ] Migrate Contract Definition Page to new Backend-For-Frontend Endpoint on API Wrapper
  - Required due to https://github.com/sovity/edc-ui/issues/228
- [ ] To refine: Next page to migrate
- [ ] Goal: Migrate entire UI to our TypeScript API Wrapper UI Endpoints and remove generated code in UI codebase.

## Initiative / goal

Some DMGMT API Endpoints simply don't have enough information for the UI, e.g. the contract agreement API. To fix these pages we thus need a custom API.

## Need for refinement
- Which endpoints / pages to migrate first.

**Comment by richardtreier** [comment]
replaced by #364
