### ISSUE TITLE
HttpDatasource: Full Support in UI

### ISSUE THREAD

**Issue by efiege** [sovity/edc-ui#28]
# Epic

## Description
The EDC-Backend offers additional properties for handling `HttpDataSource` `HttpDataSink`:
- Full configurability of provider / consumer HTTP Parameters.
- Special header "Auth" that can have it's value read from vault.
- "Proxy", share entire REST APIs by basePath.

## Breakdown
- [x] https://github.com/sovity/edc-ui/issues/103
- [x] https://github.com/sovity/edc-ui/issues/104
- [x] https://github.com/sovity/edc-ui/issues/105

## HttpSource/HttpSink Properties
| Name | Description |
|:----|:---|
| name | Name of the Address |
| path | Path added to the `baseUrl` ("/" automatically prepended) (just working in HttpSink?) |
| pathSegments | Path added to the `baseUrl` ("/" automatically prepended)  (just working in HttpSource?) |
| queryParams | QueryParams added to the request ("?" automatically prepended) |
| method | Http-Method |
| baseUrl | Base-Url the request is sent to |
| authKey | Header-Name ("Authorization"), where the secrets are passed into |
| authCode | API-Key |
| secretName | Name of the secret in the vault, used when `authCode` is not set |
| body | body that is sent with the request |
| proxyBody | Boolean, if True `body` is sent with the request |
| proxyPath | Boolean, if True `pathSegments` are sent with the request |
| proxyQueryParams | Boolean, if True `queryParams` are added to the request url |
| proxyMethod | Boolean, if True `method` property will be used |
| header:{header-name} | Additional headers to be sent |
| contentType | contentType-Header |
| nonChunkedTransfer | Boolean, if True requests is not split up (jsut working for small amounts of data ~50MB ) (just working in HttpSink? Always false in HttpSource)|

Those should be made available in the EDC-Ui.

**Comment by richardtreier** [comment]
depends on #24

for models of newer milestone
