### ISSUE TITLE
EDC 0.2.x Migration in UI + API Wrapper

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#364]
# Epic

## Description

To migrate the UI to 0.1.x, there are the following things to consider:

- The new Management API uses JSON-LD. This kind of JSON uses "@" signs etc. and is hard to create a ts model for.
- For each endpoint there is the choice between:
    - Creating new UI API Wrapper endpoints for each page and each request (preferred, but might take a bit more time during the migration). The new API calls would be type-safe thanks to the API wrapper. JSON-LD would be handled in edc-extensions. We need to migrate everything to the API wrapper so we can have dedicated UI endpoint anyways.
    - Adjusting the broken old management api to handle JSON-LD which might need intermediate layers due to the way the json is built in ways you can't create TS Interfaces with it well. This is only worth it if it considerably would reduce the time to migrate the UI, e.g. if migrating the UI would suddenly only take a single day.
    - These above two points should be decided for each request. In general we could also clean up the generated code and create API services in the UI that are more cleaned up, which would use the Angular HttpClient, e.g for DELETE calls, etc.
    - So either way in the end we should have a cleaned up API model + API services in the UI.

##  Needs Refinement
- [ ] It is possible that creating API Wrapper endpoints for some endpoints might not be the way to go.

```[tasklist]
### Tasks
- [ ] https://github.com/sovity/edc-extensions/pull/465
- [ ] https://github.com/sovity/edc-ui/issues/420
- [ ] https://github.com/sovity/edc-ui/issues/416
- [ ] https://github.com/sovity/edc-ui/issues/422
- [ ] https://github.com/sovity/edc-ui/issues/399
- [ ] https://github.com/sovity/edc-ui/issues/404
- [ ] https://github.com/sovity/edc-extensions/issues/387
- [ ] https://github.com/sovity/edc-extensions/issues/482
- [ ] https://github.com/sovity/edc-ui/issues/479
```
