### ISSUE TITLE
Migrate Policy-Related Endpoints to EDC 0 with API Wrapper

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#399]
Dealing with JSON-LD in Angular templates does not work, so before we add an intermediate layer into our UI we want to deal with the JSON-LD in our UI API Wrapper. Thus we want to add a new endpoint to type safely use the EDC Version 0 APIs from our UI.

Especially for the PolicyDto, which we need to re-interpret, we should interpret it in the backend, rather than the frontend.

With recommendation of @efiege we'll assume a policy to be:

```java
class PolicyDto {
  String legacyJsonLd;
  List<ConstraintDto> constraints;

  // If the above reduction to a list of constraints/permissions did not work
  List<String> errorMessages;
}
```
```[tasklist]
### Tasks
- [ ] https://github.com/sovity/edc-ui/issues/427
- [ ] https://github.com/sovity/edc-ui/issues/330
- [ ] https://github.com/sovity/edc-ui/issues/410
- [ ] https://github.com/sovity/edc-ui/issues/389
- [ ] https://github.com/sovity/edc-ui/issues/333
- [ ] https://github.com/sovity/edc-ui/issues/334
- [ ] #406
- [ ] https://github.com/sovity/edc-ui/issues/398
- [ ] https://github.com/sovity/edc-ui/issues/403
- [ ] https://github.com/sovity/edc-ui/issues/418
- [ ] https://github.com/sovity/edc-ui/issues/393
- [ ] https://github.com/sovity/edc-ui/issues/468
- [ ] https://github.com/sovity/edc-ui/issues/469
- [ ] https://github.com/sovity/edc-ui/issues/470
- [ ] https://github.com/sovity/edc-ui/issues/471
```
