### ISSUE TITLE
Migrate Contract Definition Page to EDC 0 with API Wrapper

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#416]
```[tasklist]
### Tasks
- [ ] https://github.com/sovity/edc-ui/issues/409
- [ ] https://github.com/sovity/edc-ui/issues/332
- [ ] https://github.com/sovity/edc-ui/issues/391
- [ ] https://github.com/sovity/edc-ui/issues/394
- [ ] https://github.com/sovity/edc-ui/issues/417
- [ ] https://github.com/sovity/edc-ui/issues/396
- [ ] https://github.com/sovity/edc-ui/issues/429
```
