### ISSUE TITLE
Migrate Transfer History to EDC 0 with API Wrapper

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#422]
```[tasklist]
### Tasks
- [ ] https://github.com/sovity/edc-ui/issues/261
- [ ] https://github.com/sovity/edc-ui/issues/262
- [ ] https://github.com/sovity/edc-ui/pull/351
- [ ] https://github.com/sovity/edc-ui/issues/231
- [ ] https://github.com/sovity/edc-ui/issues/433
```
