### ISSUE TITLE
Manually Test EDC 0 Asset Page: List, Create, Delete

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#428]
```[tasklist]
### Tasks
- [x] Manually test "Create Asset" with the `edc-extensions/docker-compose-dev.yaml`
- [x] Manually test "List Assets" with the `edc-extensions/docker-compose-dev.yaml`
- [x] Manually test "Delete Asset" with the `edc-extensions/docker-compose-dev.yaml`
- [x] Implement Fixes (if required)
```
