### ISSUE TITLE
Manually Test EDC 0 Contract Definition Page: List, Create, Delete

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#429]
```[tasklist]
### Tasks
- [x] Manually test "Create Contract Definition" with the `edc-extensions/docker-compose-dev.yaml`
- [x] Manually test "List Contract Definitions" with the `edc-extensions/docker-compose-dev.yaml`
- [x] Manually test "Delete Contract Definition" with the `edc-extensions/docker-compose-dev.yaml`
- [x] Implement Fixes (if required)
```
