### ISSUE TITLE
Release v0.0.1-milestone-8-sovity13

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#464]
# Release

This release is based on the `ms8` branch instead of the main branch.

## Work Breakdown

Feel free to edit this release checklist in-progress depending on what tasks need to be done:
- [x] Decide a release version depending on the previous release.
- [x] Update this issue's title to the new version
- [x] `release-prep` PR:
  - [ ] Update the CHANGELOG.md.
    - [x] Add a clean `Unreleased` version.
    - [x] Add the version to the old section.
    - [x] Add the current date to the old version.
    - [x] Write or review a `Deployment Migration Notes` section.
    - [x] Write or review a release summary.
    - [x] Remove empty sections from the patch notes.
  - [x] Merge the `release-prep` PR.
- [x] Wait for the main branch to be green.
- [x] Create a release and re-use the changelog section as release description, and the version as title.
- [x] Check if the pipeline built the release versions in the Actions-Section (or you won't see it).
- [x] Revisit the changed list of tasks and compare it with [.github/ISSUE_TEMPLATE/release.md](https://github.com/sovity/edc-ui/blob/main/.github/ISSUE_TEMPLATE/release.md). Propose changes where it
  makes sense.
- [x] Close this issue.
