### ISSUE TITLE
Warning about not correctly configured Logging House extension for MDS variant

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-ui#677]
# Feature Request

## Description

- When a user accesses the EDC frontend in MDS configuration, this user should be warned if the [Logging House extension](https://github.com/sovity/edc-extensions/pull/732) is not active. 
- This user should also be warned if necessary parameters of the extension are not set (e.g. URL) or obviously wrong set (e.g. URL=no_protocol.eu/log)

## Which Areas Would Be Affected?

- EDC API Wrapper
- EDC UI (MDS version)

## Why Is the Feature Desired?
MDS requires Logging House to be activated. Users shall be hinted, that the EDC is not correctly configured for MDS - thus avoiding unintentional mistakes in cofiguration.

## How does this tie into our current product?
MDS EDC

## Stakeholders
@ip312 @DanielHeiderMDS @jkbquabeck 

## Solution Proposal and Work Breakdown

```[tasklist]
- [ ] Fix the GitHub Projects Labels, Sprint and other Metadata
- [ ] Refine a Solution Proposal / Work Breakdown
```

## Tasks
- [ ] Create rough work breakdown structure 
- [ ] Create effort estimation
