### ISSUE TITLE
Markdown support for fields `Reference files description` and `Conditions for use`

### ISSUE THREAD

**Issue by SebastianOpriel** [sovity/edc-ui#759]
Adjust fields:
-  Reference files description
- Conditions for use
to be processed as Markdown.

![image](https://github.com/sovity/edc-ui/assets/22075788/e9b1a464-40ea-4c4c-8858-16cc4c85723f)

```[tasklist]
### Tasks
- [ ] EDC-UI: Add markdown support for `reference files description` field
- [ ] EDC-UI: Add markdown support for `Conditions for use` field
- [ ] Adjust field info on creation: Add hint about markdown support
- [ ] If necessary adjust field info on edit page.
- [ ] EDC-UI: Add markdown processing in asset details view
- [ ] Authority Portal: Add markdown processing in asset details view
```
