### ISSUE TITLE
Enhance with Test IDs

### ISSUE THREAD

**Issue by richardtreier** [sovity/edc-ui#805]
To streamline E2E Test development we need Test IDs on everything.

For newer developments, this can be enforced through PRs,  but for existing stuff we need to go through it once:

```[tasklist]
### Tasks
- [ ] Decide on a Test ID format. Preferably `data-testid`
- [ ] All buttons need a Test ID, preferably enforced by a custom component as API surface
- [ ] All inputs need a Test ID, preferably enforced by a custom component as API surface
- [ ] All Checkbox / Radio Button **options** need a Test ID
- [ ] Non-changing drop down **options** preferably get a Test ID
- [ ] Menu Items need a Test ID
- [ ] All major output fields would profit from getting a Test ID, e.g. "Description Text", "Labels"
- [ ] All Property Grid Groups need a Test ID
```
