### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by illfixit** [sovity/edc-ui#848]
```[tasklist]
### Tasks
- [x] Initial i18n fixes
- [x] Dashboard page
- [x] Create Data Offer Page
- [x] Assets Page :: main
- [x] Assets Page :: Create New Asset Dialog
- [x] Policies Page :: main
- [x] Policies Page :: Create New Policy Dialog (not possible in current DRY configuration due to Angular)
- [x] Data Offers Page :: main
- [x] Data Offers Page :: Create Data Offer
- [x] Catalog Browser :: main
- [x] Catalog Browser :: Cards
- [x] Contracts :: main
- [x] Contracts :: Cards
- [x] Transfer History :: main
- [x] Transfer History :: Details Dialog
- [x] Refactor
- [x] Dashboard page
- [x] Create Data Offer Page
- [x] Assets Page :: main
- [x] Assets Page :: Create New Asset Dialog
- [x] Policies Page :: main
- [x] Policies Page :: Create New Policy Dialog (not possible in current DRY configuration due to Angular)
- [x] Data Offers Page :: main
- [x] Data Offers Page :: Create Data Offer
- [x] Catalog Browser :: main
- [x] Catalog Browser :: Cards
- [x] Contracts :: main
- [x] Contracts :: Cards
- [x] Transfer History :: main
- [x] Transfer History :: Details Dialog
```
